// Wait for DOM to be fully loaded
document.addEventListener('DOMContentLoaded', function() {
    // Toggle mobile menu when hamburger is clicked
    document.querySelector('.hamburger-menu').addEventListener('click', function() {
        this.classList.toggle('opened');
        document.querySelector('.nav-menu').classList.toggle('active');
    });
    
    // Load gallery images dynamically
    loadGalleryImages();
});

// Function to load photos from the JSON file
async function loadGalleryImages() {
  const galleryGrid = document.querySelector('.gallery .grid');
  
  // Set loading indicator with spinner
  galleryGrid.innerHTML = '<p class="loading"><span class="spinner"></span>Loading images...</p>';

  try {
    // Fetch the JSON file generated by the GitHub Action
    const response = await fetch('photos-list.json');
    
    if (!response.ok) {
      throw new Error(`Failed to load photos list: ${response.status} ${response.statusText}`);
    }
    
    const data = await response.json();
    
    // Clear any existing content
    galleryGrid.innerHTML = '';
    
    // Check if we have photos
    if (data.photos && data.photos.length > 0) {
      // Loop through each photo and create gallery items
      data.photos.forEach(photo => {
        const photoLink = document.createElement('a');
        photoLink.href = photo.path; // Use the path as the link href for fullscreen view
        photoLink.target = '_blank';
        
        const img = document.createElement('img');
        img.src = photo.path;
        img.alt = photo.file.split('.')[0].replace(/-|_/g, ' '); // Convert filename to alt text
        img.loading = 'lazy'; // Use lazy loading for better performance
        
        // Add error handling for image loading
        img.onerror = function() {
          this.onerror = null;
          this.src = 'https://placehold.co/600x400?text=Image+Not+Found';
          this.alt = 'Image not found';
        };
        
        photoLink.appendChild(img);
        galleryGrid.appendChild(photoLink);
      });
    } else {
      // Display a message if no photos are found
      const noPhotosElement = document.createElement('p');
      noPhotosElement.textContent = 'No photos available in the gallery.';
      galleryGrid.appendChild(noPhotosElement);
    }
  } catch (error) {
    console.error('Error loading gallery images:', error);
    
    const errorElement = document.createElement('p');
    errorElement.textContent = 'Failed to load gallery images. Please try again later.';
    errorElement.className = 'error-message';
    
    galleryGrid.innerHTML = '';
    galleryGrid.appendChild(errorElement);
  }
} 