name: Generate Photos List

on:
  push:
    paths:
      - 'photos/**'
    branches:
      - main
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  generate-photos-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List photos directory
        id: list-photos
        run: |
          echo "Generating photos list..."
          PHOTOS_JSON="{\"photos\":["
          
          first=true
          # Use nullglob to prevent errors when no files match a pattern
          shopt -s nullglob
          
          # Process all images in the photos directory
          for file in photos/*.jpg photos/*.jpeg photos/*.png photos/*.gif photos/*.webp; do
            if [[ -f "$file" ]]; then
              if [[ "$first" == true ]]; then
                first=false
              else
                PHOTOS_JSON="$PHOTOS_JSON,"
              fi
              filename=$(basename "$file")
              PHOTOS_JSON="$PHOTOS_JSON{\"file\":\"$filename\",\"path\":\"photos/$filename\"}"
            fi
          done
          
          # Reset shell option
          shopt -u nullglob
          
          PHOTOS_JSON="$PHOTOS_JSON]}"
          echo "$PHOTOS_JSON" > photos-list.json
          echo "Generated photos list successfully."

      - name: Commit and push photos list
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add photos-list.json
          git commit -m "Update photos list" || echo "No changes to commit"
          git push